// Get Inventory
export const INVENTORY_GET_STARTED = 'INVENTORY_GET_STARTED';
export const INVENTORY_GET_SUCCESS = 'INVENTORY_GET_SUCCESS';
export const INVENTORY_GET_FAILURE = 'INVENTORY_GET_FAILURE';