export const constants = {
  TOTAL_SALES__METRICS: 'TOTAL_SALES',
	GROSS_PROFIT__METRICS: 'GROSS_PROFIT',
	AVERAGE_MARGIN__METRICS: 'AVERAGE_MARGIN',
	NUMBER_OF_ORDERS__METRICS: 'NUMBER_OF_ORDERS',
	AVERAGE_ORDER_VALUE__METRICS: 'AVERAGE_ORDER_VALUE',
	REORDER_FREQUENCY__METRICS: 'REORDER_FREQUENCY',
	REPEAT_RATE__METRICS: 'REPEAT_RATE',
}



const METRICS = [
  constants.TOTAL_SALES__METRICS,
  constants.GROSS_PROFIT__METRICS,
  constants.AVERAGE_MARGIN__METRICS,
  constants.NUMBER_OF_ORDERS__METRICS,
  constants.AVERAGE_ORDER_VALUE__METRICS,
  constants.REORDER_FREQUENCY__METRICS,
  constants.REPEAT_RATE__METRICS
];

const VENDOR__CONTEXT = 'vendor';
const CUSTOMER__CONTEXT = 'customer';
const PRODUCT__CONTEXT = 'product';
const VARIANT__CONTEXT = 'variant';
const CATEGORY__CONTEXT = 'category';

const METRIC_CONTEXT_MAPPING = {
  [constants.TOTAL_SALES__METRICS]: [VENDOR__CONTEXT, VARIANT__CONTEXT, CUSTOMER__CONTEXT, PRODUCT__CONTEXT, CATEGORY__CONTEXT],
  [constants.GROSS_PROFIT__METRICS]: [VENDOR__CONTEXT, CUSTOMER__CONTEXT, PRODUCT__CONTEXT, VARIANT__CONTEXT, CATEGORY__CONTEXT],
  [constants.AVERAGE_MARGIN__METRICS]: [VENDOR__CONTEXT, CUSTOMER__CONTEXT, PRODUCT__CONTEXT, VARIANT__CONTEXT, CATEGORY__CONTEXT],
  [constants.NUMBER_OF_ORDERS__METRICS]: [VENDOR__CONTEXT, CUSTOMER__CONTEXT, PRODUCT__CONTEXT, VARIANT__CONTEXT, CATEGORY__CONTEXT],
  [constants.AVERAGE_ORDER_VALUE__METRICS]: [CUSTOMER__CONTEXT],
  [constants.REORDER_FREQUENCY__METRICS]: [VENDOR__CONTEXT, CUSTOMER__CONTEXT, PRODUCT__CONTEXT, VARIANT__CONTEXT, CATEGORY__CONTEXT],
  [constants.REPEAT_RATE__METRICS]: [VENDOR__CONTEXT, PRODUCT__CONTEXT, VARIANT__CONTEXT, CATEGORY__CONTEXT]
};

const GOAL_STATUS = {
  DELETED: 'DELETED',
  INACTIVE: 'INACTIVE',
  ACTIVE: 'ACTIVE',
  ONGOING: 'ONGOING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
};


export const GoalConstants ={
  METRICS,
  VENDOR__CONTEXT,
  CUSTOMER__CONTEXT,
  PRODUCT__CONTEXT,
  VARIANT__CONTEXT,
  CATEGORY__CONTEXT,
  METRIC_CONTEXT_MAPPING,
  GOAL_STATUS,
};