export const GET_METRICS_REQUEST = 'GET_METRICS_REQUEST';
export const GET_METRICS_SUCCESS = 'GET_METRICS_SUCCESS';
export const GET_METRICS_ERROR = 'GET_METRICS_ERROR';

export const GET_METRICS_DATA_BY_NAME_REQUEST = 'GET_METRICS_DATA_BY_NAME_REQUEST';
export const GET_METRICS_DATA_BY_NAME_SUCCESS = 'GET_METRICS_DATA_BY_NAME_SUCCESS';
export const GET_METRICS_DATA_BY_NAME_ERROR = 'GET_METRICS_DATA_BY_NAME_ERROR';

export const GET_CHART_DATA_REQUEST = 'GET_CHART_DATA_REQUEST';
export const GET_CHART_DATA_SUCCESS = 'GET_CHART_DATA_SUCCESS';
export const GET_CHART_DATA_ERROR = 'GET_CHART_DATA_ERROR';

export const EMPTY_TIME_FRAME_DATA = 'EMPTY_TIME_FRAME_DATA';

export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_VARIANTS_REQUEST = 'GET_VARIANTS_REQUEST';
export const GET_VARIANTS_SUCCESS = 'GET_VARIANTS_SUCCESS';
export const GET_VARIANTS_ERROR = 'GET_VARIANTS_ERROR';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const GET_CHANNEL_REQUEST = 'GET_CHANNEL_REQUEST';
export const GET_CHANNEL_SUCCESS = 'GET_CHANNEL_SUCCESS';
export const GET_CHANNEL_ERROR = 'GET_CHANNEL_ERROR';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const GET_PRODUCTS_COUNT_REQUEST = 'GET_PRODUCTS_COUNT_REQUEST';
export const GET_PRODUCTS_COUNT_SUCCESS = 'GET_PRODUCTS_COUNT_SUCCESS';
export const GET_PRODUCTS_COUNT_ERROR = 'GET_PRODUCTS_COUNT_ERROR';

export const GET_VENDORS_REQUEST = 'GET_VENDORS_REQUEST';
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';
export const GET_VENDORS_ERROR = 'GET_VENDORS_ERROR';

export const GET_PRODUCT_BY_SINGLE_CATEGORY_REQUEST = `GET_PRODUCT_BY_SINGLE_CATEGORY_REQUEST`;
export const GET_PRODUCT_BY_SINGLE_CATEGORY_SUCCESS = `GET_PRODUCT_BY_SINGLE_CATEGORY_SUCCESS`;
export const GET_PRODUCT_BY_SINGLE_CATEGORY_ERROR = `GET_PRODUCT_BY_SINGLE_CATEGORY_ERROR`;

export const GET_VARIANT_BY_SINGLE_PRODUCT_REQUEST = `GET_VARIANT_BY_SINGLE_PRODUCT_REQUEST`;
export const GET_VARIANT_BY_SINGLE_PRODUCT_SUCCESS = `GET_VARIANT_BY_SINGLE_PRODUCT_SUCCESS`;
export const GET_VARIANT_BY_SINGLE_PRODUCT_ERROR = `GET_VARIANT_BY_SINGLE_PRODUCT_ERROR`;

export const GET_TIME_BY_SINGLE_VARIANT_REQUEST = `GET_TIME_BY_SINGLE_VARIANT_REQUEST`;
export const GET_TIME_BY_SINGLE_VARIANT_SUCCESS = `GET_TIME_BY_SINGLE_VARIANT_SUCCESS`;
export const GET_TIME_BY_SINGLE_VARIANT_ERROR = `GET_TIME_BY_SINGLE_VARIANT_ERROR`;

export const GET_DATA_LOAD_STATUS_SUCCESS = 'GET_DATA_LOAD_STATUS_SUCCESS';
export const GET_DATA_LOAD_STATUS_ERROR = 'GET_DATA_LOAD_STATUS_ERROR';

export const GET_CLEAR_CHARTDATA_SUCCESS = 'GET_CLEAR_CHARTDATA_SUCCESS';

export const GET_CONNECT_SHOPIFY_ALERT_SUCCESS = 'GET_CONNECT_SHOPIFY_ALERT_SUCCESS';

export const GET_LAST_UPDATED_TIMESTAMP_SUCCESS = 'GET_LAST_UPDATED_TIMESTAMP_SUCCESS';

//goals
export const  GET_ACTIVE_GOALS_DATA_REQUEST = 'GET_ACTIVE_GOALS_DATA_REQUEST';
export const  GET_ACTIVE_GOALS_DATA_SUCCESS = 'GET_ACTIVE_GOALS_DATA_SUCCESS';
export const  GET_ACTIVE_GOALS_DATA_ERROR = 'GET_ACTIVE_GOALS_DATA_ERROR';

export const  GET_ALL_GOALS_DATA_REQUEST = 'GET_ALL_GOALS_DATA_REQUEST';
export const  GET_ALL_GOALS_DATA_SUCCESS = 'GET_ALL_GOALS_DATA_SUCCESS';
export const  GET_ALL_GOALS_DATA_ERROR = 'GET_ALL_GOALS_DATA_ERROR';

export const SAVE_GOAL_REQUEST = 'SAVE_GOAL_REQUEST';
export const SAVE_GOAL_SUCCESS = 'SAVE_GOAL_SUCCESS';
export const SAVE_GOAL_ERROR = 'SAVE_GOAL_ERROR';

export const ADD_GOAL_REQUEST = 'ADD_GOAL_REQUEST';
export const ADD_GOAL_SUCCESS = 'ADD_GOAL_SUCCESS';
export const ADD_GOAL_ERROR = 'ADD_GOAL_ERROR';

export const DELETE_GOAL_REQUEST = 'DELETE_GOAL_REQUEST';
export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_ERROR = 'DELETE_GOAL_ERROR';


export const ARCHIVE_GOAL_REQUEST = 'ARCHIVE_GOAL_REQUEST';
export const ARCHIVE_GOAL_SUCCESS = 'ARCHIVE_GOAL_SUCCESS';
export const ARCHIVE_GOAL_ERROR = 'ARCHIVE_GOAL_ERROR';

export const SHOW_EDIT_GOAL_MODAL = 'SHOW_EDIT_GOAL_MODAL';
export const HIDE_EDIT_GOAL_MODAL = 'HIDE_EDIT_GOAL_MODAL';

export const ON_ADD_GOAL_REQUEST ="ON_ADD_GOAL_REQUEST";
export const ON_ADD_GOAL_SUCCESS ="ON_ADD_GOAL_SUCCESS";
export const ON_ADD_GOAL_ERROR ="ON_ADD_GOAL_ERROR";
export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR="UPDATE_USER_ERROR"

export const GET_TIMEZONE_SUCCESS="UPDATE_USER_SUCCESS"

