export const GET_METRICS_REQUEST = 'GET_METRICS_REQUEST';
export const GET_METRICS_SUCCESS = 'GET_METRICS_SUCCESS';
export const GET_METRICS_ERROR = 'GET_METRICS_ERROR';

export const GET_CHART_DATA_REQUEST = 'GET_CHART_DATA_REQUEST';
export const GET_CHART_DATA_SUCCESS = 'GET_CHART_DATA_SUCCESS';
export const GET_CHART_DATA_ERROR = 'GET_CHART_DATA_ERROR';

export const EMPTY_TIME_FRAME_DATA = 'EMPTY_TIME_FRAME_DATA';

export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';
